name: Build and deploy .NET application to Container App silo

on:
  push:
    branches:
    - deploy

env:
  
  # alphanumeric string under 14 characters
  RESOURCE_GROUP_NAME: defendermarkii

  # specify your preferred region
  REGION: westeurope

  SVC_DOCKER: src/BeneficiaryNameValidationSvc/Dockerfile
  SVC_IMAGE: beneficiarynamevalidationsvc

jobs:
  # provision:
  #   runs-on: ubuntu-latest

  #   steps:

  #   - name: Checkout to the branch
  #     uses: actions/checkout@v2

  #   - name: Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AzureSPN }}

  #   - name: Create resource group
  #     uses: azure/CLI@v1
  #     with:
  #       inlineScript: >
  #         echo "Creating resource group in Azure"
  #         echo "Executing 'az group create -l ${{ env.REGION }} -n ${{ env.RESOURCE_GROUP_NAME }}'"

  #         az group create -l ${{ env.REGION }} -n ${{ env.RESOURCE_GROUP_NAME }}

  #   - name: Creating resources
  #     uses: azure/CLI@v1
  #     with:
  #       inlineScript: >
  #         echo "Creating resources"

  #         az deployment group create --resource-group ${{ env.RESOURCE_GROUP_NAME }} --template-file '/github/workspace/Azure/main.bicep' --debug

  build:
    runs-on: ubuntu-latest
    needs: provision
    
    steps:

    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AzureSPN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      run: |
        set -euo pipefail
        docker login ${{ env.RESOURCE_GROUP_NAME }}acr.azurecr.io --username ${{ secrets.SP_CLIENT_ID }} --password ${{ secrets.SP_CLIENT_SECRET }}

    - name: Build the api image and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.RESOURCE_GROUP_NAME }}acr.azurecr.io/${{ env.SVC_IMAGE }}:${{ github.sha }}
        file: ${{ env.SVC_DOCKER }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AzureSPN }}

    - name: Installing Container Apps extension
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az extension add --name containerapp --yes

    - name: Login to ACR
      run: |
        set -euo pipefail
        docker login ${{ env.RESOURCE_GROUP_NAME }}acr.azurecr.io --username ${{ secrets.SP_CLIENT_ID }} --password ${{ secrets.SP_CLIENT_SECRET }}

    - name: Deploy Container Apps
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az containerapp registry set -n beneficiarynamevalidationsvc -g ${{ env.RESOURCE_GROUP_NAME }} --server ${{ env.RESOURCE_GROUP_NAME }}acr.azurecr.io

          az containerapp update -n beneficiarynamevalidationsvc -g ${{ env.RESOURCE_GROUP_NAME }} -i ${{ env.RESOURCE_GROUP_NAME }}acr.azurecr.io/${{ env.SVC_IMAGE }}:${{ github.sha }}

    - name: logout
      run: >
        az logout
